name: erc20
description: Interface of the ERC20 standard as defined in the EIP-20 Token Standard.
version: 1.0.0
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_erc20/
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web3dart:
    git:
      url: https://github.com/quytran0311/web3dart.git
      ref: main

dev_dependencies:
  test: ^1.20.0
  lints: ^1.0.0
